# ─── Fuente (Nerd Font con iconos) ───
# font_family      JetBrainsMono Nerd Font
# bold_font        JetBrainsMono Nerd Font Bold
# italic_font      JetBrainsMono Nerd Font Italic
font_size        12.0

# ─── Transparencia efecto cristal ───
background_opacity 0.92
dynamic_background_opacity yes
# Difuminado de fondo (solo lo aplica el compositor; picom lo hará)

# ─── Cursor ───
cursor_shape beam
cursor_blink_interval 0.5

# ─── Padding interior (aire, más elegante) ───
window_padding_width 12

# ─── Scrollback ───
scrollback_lines 10000

# ─── Sin campana molesta ───
enable_audio_bell no

# ─── Pestañas ───
tab_bar_style powerline
tab_powerline_style slanted

# ─── Tema Tokyo Night (tonos azules) ───
foreground            #c0caf5
background            #1a1b26
selection_foreground  #1a1b26
selection_background  #c0caf5

cursor                #c0caf5
cursor_text_color     #1a1b26

# Negros
color0  #15161e
color8  #414868
# Rojos
color1  #f7768e
color9  #f7768e
# Verdes
color2  #9ece6a
color10 #9ece6a
# Amarillos
color3  #e0af68
color11 #e0af68
# Azules
color4  #7aa2f7
color12 #7aa2f7
# Magentas
color5  #bb9af7
color13 #bb9af7
# Cianes
color6  #7dcfff
color14 #7dcfff
# Blancos
color7  #a9b1d6
color15 #c0caf5

# Bordes de ventana activa/inactiva
active_border_color   #7aa2f7
inactive_border_color #414868

# Título de pestañas
active_tab_foreground   #1a1b26
active_tab_background   #7aa2f7
inactive_tab_foreground #c0caf5
inactive_tab_background #24283b


# BEGIN_KITTY_FONTS
font_family      family="JetBrainsMono Nerd Font Mono"
bold_font        auto
italic_font      auto
bold_italic_font auto
# END_KITTY_FONTS